name: Build and analyze WinForms app on SonarCloud

on:
  push:
    branches:
      
master
pull_request:
  types: [opened, synchronize, reopened]
  branches:
'*'

jobs:
  build:
    name: Build and analyze on SonarCloud
    runs-on: windows-latest

    steps:
      
name: Checkout code
      uses: actions/checkout@v3

      
name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

      
name: Setup NuGet
      uses: NuGet/setup-nuget@v1

      
name: Restore NuGet packages
      run: nuget restore MiProyectoWinForms.sln

      
name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

      
name: Begin SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin /k:"jassiel-13_Repositorio-3.0" /o:"jassiel-13" /d:sonar.login="91b1477bc90b39cb62b1a7e33592f1dbec351a8f"

      
name: Build with MSBuild
      run: msbuild MiProyectoWinForms.sln /p:Configuration=Release

      
name: Run Unit Tests (opcional)
      run: |
        vstest.console.exe "Tests\bin\Release\Tests.dll"

      
name: End SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.login="91b1477bc90b39cb62b1a7e33592f1dbec351a8f"
